version: '3'

services: 
  rancher:
    build:
      context: ./rancher
    restart: on-failure
    ports: 
      - 8080:8080
      - 80:80
      - 443:443
    networks: 
      - backend
      
networks: 
  backend:
    driver: bridge